name: Python CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install uv
          python -m pip install --upgrade pip
          pip install -e ".[dev]"

      - name: Run linter
        run: make check

      - name: Run tests without coverage
        run: make test

      - name: Check pytest plugins
        run: pytest --trace-config

      - name: Run tests with coverage
        run: make test-coverage
